package io.github.tedpaulsen.chess.lib.movegen;

import io.github.tedpaulsen.chess.lib.BoardRepresentation;
import io.github.tedpaulsen.chess.lib.Side;
import io.github.tedpaulsen.chess.lib.TestBase;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class PawnMoveGenTest extends TestBase {

    @Test
    public void testPawnMoves() {
        var b = BoardRepresentation.fromFen("R6n/2q1rp2/1p1p1kp1/1P6/2P1p3/5PP1/3P2K1/b7 w - - 4 24");
        Assertions.assertEquals(
            """
            8 ........
            7 ........
            6 ........
            5 ..1.....
            4 ...1111.
            3 ...1....
            2 ........
            1 ........
              abcdefgh""",
            generatePawnTargets(Side.WHITE, b).toString()
        );
    }

    @Test
    public void testPawnAdvanceMoves() {
        var b = BoardRepresentation.fromFen("4k3/R1q3P1/2p5/4P3/p1P5/P7/8/6K1 w - - 4 24");
        Assertions.assertEquals(
            """
            8 ......1.
            7 ........
            6 ....1...
            5 ..1.....
            4 ........
            3 ........
            2 ........
            1 ........
              abcdefgh""",
            generatePawnTargets(Side.WHITE, b).toString()
        );
    }

    @Test
    public void testPawnRightCapture() {
        var b = BoardRepresentation.fromFen("4k1Nq/6P1/5N2/4P3/Rpp5/P7/8/6K1 w - - 4 24");
        Assertions.assertEquals(
            """
            8 .......1
            7 ........
            6 ....1...
            5 ........
            4 .1......
            3 ........
            2 ........
            1 ........
              abcdefgh""",
            generatePawnTargets(Side.WHITE, b).toString()
        );
    }

    @Test
    public void testPawnLeftCapture() {
        var b = BoardRepresentation.fromFen("4k1N1/8/8/8/Rpp5/2P1qN2/5P2/6K1 w - - 4 24");
        Assertions.assertEquals(
            """
            8 ........
            7 ........
            6 ........
            5 ........
            4 .1......
            3 ....1...
            2 ........
            1 ........
              abcdefgh""",
            generatePawnTargets(Side.WHITE, b).toString()
        );
    }

    @Test
    public void testPawnDoubleAdvance() {
        var b = BoardRepresentation.fromFen("4k1N1/8/8/4q3/R1p5/4B3/P1P1P1P1/6K1 w - - 4 24");
        Assertions.assertEquals(
            """
            8 ........
            7 ........
            6 ........
            5 ........
            4 ......1.
            3 1.1...1.
            2 ........
            1 ........
              abcdefgh""",
            generatePawnTargets(Side.WHITE, b).toString()
        );
    }
}
