package io.github.tedpaulsen.chess.lib;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class RookMovesTest extends TestBase {

    @Test
    public void testRookMoves() {
        var board = BoardRepresentation.fromFen("5rk1/2qb1ppp/1p1p1n2/1P2p3/1BP5/4P3/3NBPPP/5RK1 w - - 4 24");
        Assertions.assertEquals(
            """
              8 ........
              7 ........
              6 ........
              5 ........
              4 ........
              3 ........
              2 ........
              1 11111...
                abcdefgh""",
            generateRookTargets(Side.WHITE, board).toString()
        );
    }
}
